spring:
  application:
    name: Picket

  datasource:
    url: jdbc:mysql://localhost:3306/picket-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

oauth:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET_KEY}
    redirect-uris:
      director: http://localhost:8080/api/v2/auth/callback/director
      user: http://localhost:8080/api/v2/auth/callback/user
      admin: http://localhost:8080/api/v2/auth/callback/admin
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo