spring:
  application:
    name: Picket

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: ${AWS_REDIS_URL}
      port: ${AWS_REDIS_PORT}

oauth:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET_KEY}
    redirect-uris :
      director: http://localhost:8080/api/v2/auth/callback/director
      user: http://localhost:8080/api/v2/auth/callback/user
      admin: http://localhost:8080/api/v2/auth/callback/admin
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo