spring:
  application:
    name: Picket

  datasource:
    url: jdbc:mysql://localhost:3306/picket-mysql?rewriteBatchedStatements=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 60m

oauth:
  google:
    client-id: dummy-client-id
    client-secret: dummy-client-secret
    redirect-uris :
      director: http://localhost:8080/api/v2/auth/callback/director
      user: http://localhost:8080/api/v2/auth/callback/user
      admin: http://localhost:8080/api/v2/auth/callback/admin
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

cloud:
  aws:
    credentials:
      access-key: dummy-access-key
      secret-key: dummy-secret-key
    s3:
      bucket: dummy-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  region: ap-northeast-2
  ses:
    access-key: dummy-ses-access-key
    secret-key: dummy-ses-secret-key
    send-mail-from: dummy@example.com