spring:
  application:
    name: Picket

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${AWS_REDIS_URL}
      port: ${AWS_REDIS_PORT}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 60m

# monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true

#Google OAuth
oauth:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET_KEY}
    redirect-uris:
      director: https://thepickets.com/api/v2/auth/callback/director
      user: https://thepickets.com/api/v2/auth/callback/user
      admin: https://thepickets.com/api/v2/auth/callback/admin
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

#AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_IMAGE_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

#AWS SES
aws:
  region: ${AWS_REGION}
  ses:
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    send-mail-from: ${AWS_SES_ADMIN_EMAIL}