spring:
  application:
    name: Picket

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: ${AWS_REDIS_URL}
      port: ${AWS_REDIS_PORT}